// <auto-generated />
namespace EmployeeTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelsAddedAuthentications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelsAddedAuthentications));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211426135_Models-Added-Authentications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
